/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthSidebarRouteImport } from './routes/_auth._sidebar'
import { Route as AuthSidebarIndexRouteImport } from './routes/_auth._sidebar.index'
import { Route as AuthSidebarSharedToRouteImport } from './routes/_auth._sidebar.shared.$to'
import { Route as AuthVectorOwnerIdMountIdPathIdRouteImport } from './routes/_auth.vector.$ownerId.$mountId.$pathId'
import { Route as AuthSidebarDriveOwnerIdMountIdRouteImport } from './routes/_auth._sidebar.drive.$ownerId.$mountId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSidebarRoute = AuthSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSidebarIndexRoute = AuthSidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSidebarRoute,
} as any)
const AuthSidebarSharedToRoute = AuthSidebarSharedToRouteImport.update({
  id: '/shared/$to',
  path: '/shared/$to',
  getParentRoute: () => AuthSidebarRoute,
} as any)
const AuthVectorOwnerIdMountIdPathIdRoute =
  AuthVectorOwnerIdMountIdPathIdRouteImport.update({
    id: '/vector/$ownerId/$mountId/$pathId',
    path: '/vector/$ownerId/$mountId/$pathId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSidebarDriveOwnerIdMountIdRoute =
  AuthSidebarDriveOwnerIdMountIdRouteImport.update({
    id: '/drive/$ownerId/$mountId',
    path: '/drive/$ownerId/$mountId',
    getParentRoute: () => AuthSidebarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthSidebarIndexRoute
  '/login': typeof LoginRoute
  '/shared/$to': typeof AuthSidebarSharedToRoute
  '/drive/$ownerId/$mountId': typeof AuthSidebarDriveOwnerIdMountIdRoute
  '/vector/$ownerId/$mountId/$pathId': typeof AuthVectorOwnerIdMountIdPathIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthSidebarIndexRoute
  '/login': typeof LoginRoute
  '/shared/$to': typeof AuthSidebarSharedToRoute
  '/drive/$ownerId/$mountId': typeof AuthSidebarDriveOwnerIdMountIdRoute
  '/vector/$ownerId/$mountId/$pathId': typeof AuthVectorOwnerIdMountIdPathIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/_sidebar': typeof AuthSidebarRouteWithChildren
  '/_auth/_sidebar/': typeof AuthSidebarIndexRoute
  '/_auth/_sidebar/shared/$to': typeof AuthSidebarSharedToRoute
  '/_auth/_sidebar/drive/$ownerId/$mountId': typeof AuthSidebarDriveOwnerIdMountIdRoute
  '/_auth/vector/$ownerId/$mountId/$pathId': typeof AuthVectorOwnerIdMountIdPathIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/shared/$to'
    | '/drive/$ownerId/$mountId'
    | '/vector/$ownerId/$mountId/$pathId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/shared/$to'
    | '/drive/$ownerId/$mountId'
    | '/vector/$ownerId/$mountId/$pathId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/_sidebar'
    | '/_auth/_sidebar/'
    | '/_auth/_sidebar/shared/$to'
    | '/_auth/_sidebar/drive/$ownerId/$mountId'
    | '/_auth/vector/$ownerId/$mountId/$pathId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_sidebar': {
      id: '/_auth/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthSidebarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_sidebar/': {
      id: '/_auth/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthSidebarIndexRouteImport
      parentRoute: typeof AuthSidebarRoute
    }
    '/_auth/_sidebar/shared/$to': {
      id: '/_auth/_sidebar/shared/$to'
      path: '/shared/$to'
      fullPath: '/shared/$to'
      preLoaderRoute: typeof AuthSidebarSharedToRouteImport
      parentRoute: typeof AuthSidebarRoute
    }
    '/_auth/vector/$ownerId/$mountId/$pathId': {
      id: '/_auth/vector/$ownerId/$mountId/$pathId'
      path: '/vector/$ownerId/$mountId/$pathId'
      fullPath: '/vector/$ownerId/$mountId/$pathId'
      preLoaderRoute: typeof AuthVectorOwnerIdMountIdPathIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_sidebar/drive/$ownerId/$mountId': {
      id: '/_auth/_sidebar/drive/$ownerId/$mountId'
      path: '/drive/$ownerId/$mountId'
      fullPath: '/drive/$ownerId/$mountId'
      preLoaderRoute: typeof AuthSidebarDriveOwnerIdMountIdRouteImport
      parentRoute: typeof AuthSidebarRoute
    }
  }
}

interface AuthSidebarRouteChildren {
  AuthSidebarIndexRoute: typeof AuthSidebarIndexRoute
  AuthSidebarSharedToRoute: typeof AuthSidebarSharedToRoute
  AuthSidebarDriveOwnerIdMountIdRoute: typeof AuthSidebarDriveOwnerIdMountIdRoute
}

const AuthSidebarRouteChildren: AuthSidebarRouteChildren = {
  AuthSidebarIndexRoute: AuthSidebarIndexRoute,
  AuthSidebarSharedToRoute: AuthSidebarSharedToRoute,
  AuthSidebarDriveOwnerIdMountIdRoute: AuthSidebarDriveOwnerIdMountIdRoute,
}

const AuthSidebarRouteWithChildren = AuthSidebarRoute._addFileChildren(
  AuthSidebarRouteChildren,
)

interface AuthRouteChildren {
  AuthSidebarRoute: typeof AuthSidebarRouteWithChildren
  AuthVectorOwnerIdMountIdPathIdRoute: typeof AuthVectorOwnerIdMountIdPathIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSidebarRoute: AuthSidebarRouteWithChildren,
  AuthVectorOwnerIdMountIdPathIdRoute: AuthVectorOwnerIdMountIdPathIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
