/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthWaitlistRouteImport } from './routes/_auth.waitlist'
import { Route as AuthUsersRouteImport } from './routes/_auth.users'
import { Route as AuthTeamsRouteImport } from './routes/_auth.teams'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthOnboardingRouteImport } from './routes/_auth.onboarding'
import { Route as AuthMembersRouteImport } from './routes/_auth.members'
import { Route as AuthGuestsRouteImport } from './routes/_auth.guests'
import { Route as AuthGuestSettingsRouteImport } from './routes/_auth.guest-settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWaitlistRoute = AuthWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeamsRoute = AuthTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMembersRoute = AuthMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGuestsRoute = AuthGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGuestSettingsRoute = AuthGuestSettingsRouteImport.update({
  id: '/guest-settings',
  path: '/guest-settings',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/guest-settings': typeof AuthGuestSettingsRoute
  '/guests': typeof AuthGuestsRoute
  '/members': typeof AuthMembersRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/settings': typeof AuthSettingsRoute
  '/teams': typeof AuthTeamsRoute
  '/users': typeof AuthUsersRoute
  '/waitlist': typeof AuthWaitlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/guest-settings': typeof AuthGuestSettingsRoute
  '/guests': typeof AuthGuestsRoute
  '/members': typeof AuthMembersRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/settings': typeof AuthSettingsRoute
  '/teams': typeof AuthTeamsRoute
  '/users': typeof AuthUsersRoute
  '/waitlist': typeof AuthWaitlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/guest-settings': typeof AuthGuestSettingsRoute
  '/_auth/guests': typeof AuthGuestsRoute
  '/_auth/members': typeof AuthMembersRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/teams': typeof AuthTeamsRoute
  '/_auth/users': typeof AuthUsersRoute
  '/_auth/waitlist': typeof AuthWaitlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/guest-settings'
    | '/guests'
    | '/members'
    | '/onboarding'
    | '/settings'
    | '/teams'
    | '/users'
    | '/waitlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/guest-settings'
    | '/guests'
    | '/members'
    | '/onboarding'
    | '/settings'
    | '/teams'
    | '/users'
    | '/waitlist'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/guest-settings'
    | '/_auth/guests'
    | '/_auth/members'
    | '/_auth/onboarding'
    | '/_auth/settings'
    | '/_auth/teams'
    | '/_auth/users'
    | '/_auth/waitlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/waitlist': {
      id: '/_auth/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof AuthWaitlistRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/teams': {
      id: '/_auth/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthTeamsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/members': {
      id: '/_auth/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthMembersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/guests': {
      id: '/_auth/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AuthGuestsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/guest-settings': {
      id: '/_auth/guest-settings'
      path: '/guest-settings'
      fullPath: '/guest-settings'
      preLoaderRoute: typeof AuthGuestSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthGuestSettingsRoute: typeof AuthGuestSettingsRoute
  AuthGuestsRoute: typeof AuthGuestsRoute
  AuthMembersRoute: typeof AuthMembersRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthTeamsRoute: typeof AuthTeamsRoute
  AuthUsersRoute: typeof AuthUsersRoute
  AuthWaitlistRoute: typeof AuthWaitlistRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGuestSettingsRoute: AuthGuestSettingsRoute,
  AuthGuestsRoute: AuthGuestsRoute,
  AuthMembersRoute: AuthMembersRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthTeamsRoute: AuthTeamsRoute,
  AuthUsersRoute: AuthUsersRoute,
  AuthWaitlistRoute: AuthWaitlistRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
