import {beforeAll, describe, expect, test} from 'bun:test';
import {authedRequest, driveGet, driveUpload, getTestContext} from './setup';

describe('Preview', () => {
    let token: string;
    let ownerId: string;
    const mountId = 'default';
    let rootId: string;

    beforeAll(async () => {
        const ctx = await getTestContext();
        token = ctx.alice.user.sessionToken;
        ownerId = ctx.alice.user.id;
        const root = await driveGet(token, ownerId, mountId, 'root');
        rootId = root.id;
    });

    async function uploadAndTextPreview(name: string, content: string, mimeType: string) {
        const file = new File([content], name, {type: mimeType});
        const uploaded = await driveUpload(token, ownerId, mountId, rootId, file);
        const res = await authedRequest(token, `/drive/${ownerId}/${mountId}/file/${uploaded.id}/text-preview`);
        return {res, uploaded};
    }

    test('text file returns json body preview', async () => {
        const {res} = await uploadAndTextPreview('test.txt', 'Hello world', 'text/plain');
        expect(res.status).toBe(200);
        const data = await res.json();
        expect(data.body).toContain('Hello world');
        expect(data.mode).toBe('plaintext');
    });

    test('markdown file returns rendered body', async () => {
        const {res} = await uploadAndTextPreview('test.md', '# Title\n\nSome **bold** text', 'text/markdown');
        expect(res.status).toBe(200);
        const data = await res.json();
        expect(data.body).toContain('<h1>Title</h1>');
        expect(data.body).toContain('<strong>bold</strong>');
        expect(data.mode).toBe('markdown');
    });

    test('code file returns syntax highlighted body', async () => {
        const {res} = await uploadAndTextPreview('test.json', '{"key": "value"}', 'application/json');
        expect(res.status).toBe(200);
        const data = await res.json();
        expect(data.body).toContain('key');
        expect(data.mode).toBe('code');
    });

    test('image file returns webp preview', async () => {
        // Valid 4x4 red PNG generated by sharp
        const pngBytes = new Uint8Array([
            137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,4,0,0,0,4,8,2,0,0,0,38,147,9,
            41,0,0,0,9,112,72,89,115,0,0,3,232,0,0,3,232,1,181,123,82,107,0,0,0,17,73,68,65,84,
            120,156,99,248,207,192,0,71,8,22,94,14,0,174,147,15,241,166,148,72,35,0,0,0,0,73,69,
            78,68,174,66,96,130,
        ]);
        const file = new File([pngBytes], 'pixel.png', {type: 'image/png'});
        const uploaded = await driveUpload(token, ownerId, mountId, rootId, file);
        const res = await authedRequest(token, `/drive/${ownerId}/${mountId}/file/${uploaded.id}/preview`);
        expect(res.status).toBe(200);
        expect(res.headers.get('content-type')).toBe('image/webp');
    });

    test('video file redirects to embed', async () => {
        const file = new File(['fake video'], 'clip.mp4', {type: 'video/mp4'});
        const uploaded = await driveUpload(token, ownerId, mountId, rootId, file);
        const res = await authedRequest(token, `/drive/${ownerId}/${mountId}/file/${uploaded.id}/preview`);
        // Elysia redirect — check for 302 or the redirect URL in headers
        expect([200, 302]).toContain(res.status);
    });

    test('unsupported file type returns 404', async () => {
        // Upload a file that has no preview support (non-image, non-text, non-video)
        const file = new File(['dummy'], 'data.woff2', {type: 'font/woff2'});
        const uploaded = await driveUpload(token, ownerId, mountId, rootId, file);
        const res = await authedRequest(token, `/drive/${ownerId}/${mountId}/file/${uploaded.id}/preview`);
        expect(res.status).toBe(404);
    });

    test('text file preview returns 404 from image preview endpoint', async () => {
        const file = new File(['Hello'], 'check.txt', {type: 'text/plain'});
        const uploaded = await driveUpload(token, ownerId, mountId, rootId, file);
        const res = await authedRequest(token, `/drive/${ownerId}/${mountId}/file/${uploaded.id}/preview`);
        expect(res.status).toBe(404);
    });

    test('nonexistent file returns 404', async () => {
        const res = await authedRequest(token, `/drive/${ownerId}/${mountId}/file/00000000-0000-0000-0000-000000000000/preview`);
        expect(res.status).toBe(404);
    });

    test('text preview caches result on second request', async () => {
        const {res: first, uploaded} = await uploadAndTextPreview('cached.txt', 'Cache test', 'text/plain');
        expect(first.status).toBe(200);

        const second = await authedRequest(token, `/drive/${ownerId}/${mountId}/file/${uploaded.id}/text-preview`);
        expect(second.status).toBe(200);
        const data = await second.json();
        expect(data.body).toContain('Cache test');
    });
});
