export const CURRENCIES = [
    { name: 'EUR', pos: 'before', value: '€' },
    { name: 'RMB', pos: 'before', value: '¥' },
    { name: 'US dollar', pos: 'before', value: '$' },
    { name: 'GBP', pos: 'before', value: '£' },
    { name: 'HK', pos: 'before', value: '$' },
    { name: 'JPY', pos: 'before', value: '¥' },
    { name: 'Albanian Lek', pos: 'before', value: 'Lek' },
    { name: 'Algerian Dinar', pos: 'before', value: 'din' },
    { name: 'Afghani', pos: 'after', value: 'Af' },
    { name: 'Argentine Peso', pos: 'before', value: '$' },
    { name: 'United Arab Emirates Dirham', pos: 'before', value: 'dh' },
    { name: 'Aruban Florin', pos: 'before', value: 'Afl' },
    { name: 'Omani Rial', pos: 'before', value: 'Rial' },
    { name: 'Azerbaijani manat', pos: 'before', value: '₼' },
    { name: 'Egyptian Pound', pos: 'before', value: '£' },
    { name: 'Ethiopian Birr', pos: 'before', value: 'Birr' },
    { name: 'Angola Kwanza', pos: 'before', value: 'Kz' },
    { name: 'Australian Dollar', pos: 'before', value: '$' },
    { name: 'Patacas', pos: 'before', value: 'MOP' },
    { name: 'Barbados Dollar', pos: 'before', value: '$' },
    { name: 'Papua New Guinea Kina', pos: 'before', value: 'PGK' },
    { name: 'Bahamian Dollar', pos: 'before', value: '$' },
    { name: 'Pakistan Rupee', pos: 'before', value: 'Rs' },
    { name: 'Paraguayan Guarani', pos: 'after', value: 'Gs' },
    { name: 'Bahraini Dinar', pos: 'before', value: 'din' },
    { name: 'Panamanian Balboa', pos: 'before', value: 'B/' },
    { name: 'Brazilian real', pos: 'before', value: 'R$' },
    { name: 'Belarusian ruble', pos: 'after', value: 'р' },
    { name: 'Bermudian Dollar', pos: 'before', value: '$' },
    { name: 'Bulgarian Lev', pos: 'before', value: 'lev' },
    { name: 'Iceland Krona', pos: 'before', value: 'kr' },
    { name: 'Bosnia-Herzegovina Convertible Mark', pos: 'before', value: 'KM' },
    { name: 'Polish Zloty', pos: 'after', value: 'z?' },
    { name: 'Boliviano', pos: 'before', value: 'Bs' },
    { name: 'Belize Dollar', pos: 'before', value: '$' },
    { name: 'Botswana Pula', pos: 'before', value: 'P' },
    { name: 'Not Dannuzhamu', pos: 'before', value: 'Nu' },
    { name: 'Burundi Franc', pos: 'before', value: 'FBu' },
    { name: 'North Korean Won', pos: 'before', value: '?KP' },
    { name: 'Danish Krone', pos: 'after', value: 'kr' },
    { name: 'East Caribbean Dollar', pos: 'before', value: '$' },
    { name: 'Dominica Peso', pos: 'before', value: 'RD$' },
    { name: 'Russian Ruble', pos: 'after', value: '?' },
    { name: 'Eritrean Nakfa', pos: 'before', value: 'Nfk' },
    { name: 'CFA franc', pos: 'before', value: 'CFA' },
    { name: 'Philippine Peso', pos: 'before', value: '?' },
    { name: 'Fiji Dollar', pos: 'before', value: '$' },
    { name: 'Cape Verde Escudo', pos: 'before', value: 'CVE' },
    { name: 'Falkland Islands Pound', pos: 'before', value: '£' },
    { name: 'Gambian Dalasi', pos: 'before', value: 'GMD' },
    { name: 'Congolese franc', pos: 'before', value: 'FrCD' },
    { name: 'Colombian Peso', pos: 'before', value: '$' },
    { name: 'Costa Rican Colon', pos: 'before', value: '?' },
    { name: 'Cuban Peso', pos: 'before', value: '$' },
    { name: 'Cuban convertible peso', pos: 'before', value: '$' },
    { name: 'Guyana Dollar', pos: 'before', value: '$' },
    { name: 'Kazakhstan Tenge', pos: 'before', value: '?' },
    { name: 'Haitian gourde', pos: 'before', value: 'HTG' },
    { name: 'won', pos: 'before', value: '?' },
    { name: 'Netherlands Antilles Guilder', pos: 'before', value: 'NAf.' },
    { name: 'Honduras lempiras', pos: 'before', value: 'L' },
    { name: 'Djibouti Franc', pos: 'before', value: 'Fdj' },
    { name: 'Kyrgyzstan Som', pos: 'before', value: 'KGS' },
    { name: 'Guinea Franc', pos: 'before', value: 'FG' },
    { name: 'Canadian Dollar', pos: 'before', value: '$' },
    { name: 'Ghanaian Cedi', pos: 'before', value: 'GHS' },
    { name: 'Cambodian riel', pos: 'before', value: 'Riel' },
    { name: 'Czech Koruna', pos: 'after', value: 'K?' },
    { name: 'Zimbabwe Dollar', pos: 'before', value: '$' },
    { name: 'Qatari Riyal', pos: 'before', value: 'Rial' },
    { name: 'Cayman Islands Dollar', pos: 'before', value: '$' },
    { name: 'Comorian franc', pos: 'before', value: 'CF' },
    { name: 'Kuwaiti Dinar', pos: 'before', value: 'din' },
    { name: 'Croatian Kuna', pos: 'before', value: 'kn' },
    { name: 'Kenyan Shilling', pos: 'before', value: 'Ksh' },
    { name: 'Lesotho Loti', pos: 'before', value: 'LSL' },
    { name: 'Lao Kip', pos: 'before', value: '?' },
    { name: 'Lebanese Pound', pos: 'before', value: 'L£' },
    { name: 'Lithuanian litas', pos: 'before', value: 'Lt' },
    { name: 'Libyan Dinar', pos: 'before', value: 'din' },
    { name: 'Liberian Dollar', pos: 'before', value: '$' },
    { name: 'Rwanda Franc', pos: 'before', value: 'RF' },
    { name: 'Romanian Leu', pos: 'before', value: 'RON' },
    { name: 'Malagasy Ariary', pos: 'before', value: 'Ar' },
    { name: 'Maldivian Rufiyaa', pos: 'before', value: 'Rf' },
    { name: 'Malawi Kwacha', pos: 'before', value: 'MWK' },
    { name: 'Malaysian Ringgit', pos: 'before', value: 'RM' },
    { name: 'Macedonia wearing Dinar', pos: 'before', value: 'din' },
    { name: 'Mauritius Rupee', pos: 'before', value: 'MURs' },
    { name: 'Mauritanian Ouguiya', pos: 'before', value: 'MRO' },
    { name: 'Mongolian Tugrik', pos: 'before', value: '?' },
    { name: 'Bangladeshi Taka', pos: 'before', value: '?' },
    { name: 'Peruvian Nuevo Sol', pos: 'before', value: 'S/' },
    { name: 'Myanmar Kyat', pos: 'before', value: 'K' },
    { name: 'Moldovan Leu', pos: 'before', value: 'MDL' },
    { name: 'Moroccan Dirham', pos: 'before', value: 'dh' },
    { name: 'Mozambique Metical', pos: 'before', value: 'MTn' },
    { name: 'Mexican Peso', pos: 'before', value: '$' },
    { name: 'Namibian Dollar', pos: 'before', value: '$' },
    { name: 'South African Rand', pos: 'before', value: 'R' },
    { name: 'South Sudanese Pound', pos: 'before', value: '£' },
    { name: 'Nicaragua Cordoba', pos: 'before', value: 'C$' },
    { name: 'Nepalese Rupee', pos: 'before', value: 'Rs' },
    { name: 'Nigerian Naira', pos: 'before', value: '?' },
    { name: 'Norwegian Krone', pos: 'after', value: 'kr' },
    { name: 'Georgian Lari', pos: 'before', value: 'GEL' },
    { name: 'Swedish Krona', pos: 'after', value: 'kr' },
    { name: 'Swiss Franc', pos: 'before', value: 'CHF' },
    { name: 'Serbian Dinar', pos: 'before', value: 'din' },
    { name: 'Sierra Leone', pos: 'before', value: 'SLL' },
    { name: 'Seychelles Rupee', pos: 'before', value: 'SCR' },
    { name: 'Saudi Riyal', pos: 'before', value: 'Rial' },
    { name: 'Sao Tome Dobra', pos: 'before', value: 'Db' },
    { name: 'Saint Helena pound', pos: 'before', value: '£' },
    { name: 'Sri Lanka Rupee', pos: 'before', value: 'Rs' },
    { name: 'Swaziland Lilangeni', pos: 'before', value: 'SZL' },
    { name: 'Sudanese Pound', pos: 'before', value: 'SDG' },
    { name: 'Surinamese dollar', pos: 'before', value: '$' },
    { name: 'Solomon Islands Dollar', pos: 'before', value: '$' },
    { name: 'Somali Shilling', pos: 'before', value: 'SOS' },
    { name: 'Tajikistan Somoni', pos: 'before', value: 'Som' },
    { name: 'Pacific Franc', pos: 'after', value: 'FCFP' },
    { name: 'Thai Baht', pos: 'before', value: '?' },
    { name: 'Tanzanian Shilling', pos: 'before', value: 'TSh' },
    { name: "Tongan Pa'anga", pos: 'before', value: 'T$' },
    { name: 'Trinidad and Tobago Dollar', pos: 'before', value: '$' },
    { name: 'Tunisian Dinar', pos: 'before', value: 'din' },
    { name: 'Turkish Lira', pos: 'before', value: '?' },
    { name: 'Vanuatu Vatu', pos: 'before', value: 'VUV' },
    { name: 'Guatemalan Quetzal', pos: 'before', value: 'Q' },
    { name: 'Commission Bolivar', pos: 'before', value: 'Bs' },
    { name: 'Brunei Dollar', pos: 'before', value: '$' },
    { name: 'Ugandan Shilling', pos: 'before', value: 'UGX' },
    { name: 'Ukrainian Hryvnia', pos: 'before', value: 'грн.' },
    { name: 'Uruguayan Peso', pos: 'before', value: '$' },
    { name: 'Uzbekistan som', pos: 'before', value: 'so?m' },
    { name: 'Western Samoa Tala', pos: 'before', value: 'WST' },
    { name: 'Singapore Dollar', pos: 'before', value: '$' },
    { name: 'NT', pos: 'before', value: 'NT$' },
    { name: 'New Zealand Dollar', pos: 'before', value: '$' },
    { name: 'Hungarian Forint', pos: 'before', value: 'Ft' },
    { name: 'Syrian Pound', pos: 'before', value: '£' },
    { name: 'Jamaican Dollar', pos: 'before', value: '$' },
    { name: 'Armenian Dram', pos: 'before', value: 'Dram' },
    { name: 'Yemeni Rial', pos: 'before', value: 'Rial' },
    { name: 'Iraqi Dinar', pos: 'before', value: 'din' },
    { name: 'Iranian Rial', pos: 'before', value: 'Rial' },
    { name: 'New Israeli Shekel', pos: 'before', value: '?' },
    { name: 'Indian Rupee', pos: 'before', value: '₹' },
    { name: 'Indonesian Rupiah', pos: 'before', value: 'Rp' },
    { name: 'Jordanian Dinar', pos: 'before', value: 'din' },
    { name: 'VND', pos: 'after', value: '?' },
    { name: 'Zambian Kwacha', pos: 'before', value: 'ZMW' },
    { name: 'Gibraltar Pound', pos: 'before', value: '£' },
    { name: 'Chilean Peso', pos: 'before', value: '$' },
    { name: 'CFA Franc BEAC', pos: 'before', value: 'FCFA' },
];
