import {
    getCalendarAppUrl,
    getChatAppUrl,
    getContactsAppUrl,
    getDocsAppUrl,
    getDriveAppUrl,
    getMailAppUrl,
    getSheetsAppUrl,
    getSlidesAppUrl,
    getSpaceAppUrl,
    getStickiesAppUrl,
} from '@workspace/lib/api';
import {
    Calendar,
    FileText,
    HardDrive,
    LayoutDashboard,
    Mail,
    MessageSquare,
    Presentation,
    Sheet,
    StickyNote,
    UsersRound,
} from 'lucide-react';

const apps = [
    {
        name: 'Space',
        color: 'var(--app-space-color)',
        href: getSpaceAppUrl(),
        icon: LayoutDashboard,
        description: 'Your personal workspace in the cloud',
    },
    {
        name: 'Mail',
        color: 'var(--app-mail-color)',
        href: getMailAppUrl(),
        icon: Mail,
        description: 'Check your inbox',
    },
    {
        name: 'Drive',
        color: 'var(--app-drive-color)',
        href: getDriveAppUrl(),
        icon: HardDrive,
        description: 'Browse your files',
    },
    {
        name: 'Calendar',
        color: 'var(--app-calendar-color)',
        href: getCalendarAppUrl(),
        icon: Calendar,
        description: 'Keep track of your schedule',
    },
    {
        name: 'Docs',
        color: 'var(--app-docs-color)',
        href: getDocsAppUrl(),
        icon: FileText,
        description: 'Open your documents',
    },
    {
        name: 'Sheets',
        color: 'var(--app-sheets-color)',
        href: getSheetsAppUrl(),
        icon: Sheet,
        description: 'Work with spreadsheets',
    },
    {
        name: 'Slides',
        color: 'var(--app-slides-color)',
        href: getSlidesAppUrl(),
        icon: Presentation,
        description: 'Create presentations',
    },
    {
        name: 'Stickies',
        color: 'var(--app-stickies-color)',
        href: getStickiesAppUrl(),
        icon: StickyNote,
        description: 'Map out your ideas',
    },
    {
        name: 'Chat',
        color: 'var(--app-chat-color)',
        href: getChatAppUrl(),
        icon: MessageSquare,
        description: 'Chat with your team',
    },
    {
        name: 'Contacts',
        color: 'var(--app-contacts-color)',
        href: getContactsAppUrl(),
        icon: UsersRound,
        description: 'Find your contacts',
    },
    // {
    //     name: 'People',
    //     color: 'var(--app-people-color)',
    //     href: getPeopleAppUrl(),
    //     icon: UsersRound,
    //     description: 'Manage your organization',
    // },
];

export { apps };
