/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {Route as rootRouteImport} from './routes/__root'
import {Route as LoginRouteImport} from './routes/login'
import {Route as AuthRouteImport} from './routes/_auth'
import {Route as IndexRouteImport} from './routes/index'
import {Route as AuthFilterTypeFilterIdRouteImport} from './routes/_auth.$filterType.$filterId'

const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
    id: '/_auth',
    getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any)
const AuthFilterTypeFilterIdRoute = AuthFilterTypeFilterIdRouteImport.update({
    id: '/$filterType/$filterId',
    path: '/$filterType/$filterId',
    getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute
    '/login': typeof LoginRoute
    '/$filterType/$filterId': typeof AuthFilterTypeFilterIdRoute
}

export interface FileRoutesByTo {
    '/': typeof IndexRoute
    '/login': typeof LoginRoute
    '/$filterType/$filterId': typeof AuthFilterTypeFilterIdRoute
}

export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/': typeof IndexRoute
    '/_auth': typeof AuthRouteWithChildren
    '/login': typeof LoginRoute
    '/_auth/$filterType/$filterId': typeof AuthFilterTypeFilterIdRoute
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths: '/' | '/login' | '/$filterType/$filterId'
    fileRoutesByTo: FileRoutesByTo
    to: '/' | '/login' | '/$filterType/$filterId'
    id: '__root__' | '/' | '/_auth' | '/login' | '/_auth/$filterType/$filterId'
    fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute
    AuthRoute: typeof AuthRouteWithChildren
    LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/login': {
            id: '/login'
            path: '/login'
            fullPath: '/login'
            preLoaderRoute: typeof LoginRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/_auth': {
            id: '/_auth'
            path: ''
            fullPath: ''
            preLoaderRoute: typeof AuthRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/_auth/$filterType/$filterId': {
            id: '/_auth/$filterType/$filterId'
            path: '/$filterType/$filterId'
            fullPath: '/$filterType/$filterId'
            preLoaderRoute: typeof AuthFilterTypeFilterIdRouteImport
            parentRoute: typeof AuthRoute
        }
    }
}

interface AuthRouteChildren {
    AuthFilterTypeFilterIdRoute: typeof AuthFilterTypeFilterIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
    AuthFilterTypeFilterIdRoute: AuthFilterTypeFilterIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    AuthRoute: AuthRouteWithChildren,
    LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()
