/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthInboxImport } from './routes/_auth.inbox'
import { Route as AuthInboxMailIdImport } from './routes/_auth.inbox.$mailId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthInboxRoute = AuthInboxImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthRoute,
} as any)

const AuthInboxMailIdRoute = AuthInboxMailIdImport.update({
  id: '/$mailId',
  path: '/$mailId',
  getParentRoute: () => AuthInboxRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/inbox': {
      id: '/_auth/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthInboxImport
      parentRoute: typeof AuthImport
    }
    '/_auth/inbox/$mailId': {
      id: '/_auth/inbox/$mailId'
      path: '/$mailId'
      fullPath: '/inbox/$mailId'
      preLoaderRoute: typeof AuthInboxMailIdImport
      parentRoute: typeof AuthInboxImport
    }
  }
}

// Create and export the route tree

interface AuthInboxRouteChildren {
  AuthInboxMailIdRoute: typeof AuthInboxMailIdRoute
}

const AuthInboxRouteChildren: AuthInboxRouteChildren = {
  AuthInboxMailIdRoute: AuthInboxMailIdRoute,
}

const AuthInboxRouteWithChildren = AuthInboxRoute._addFileChildren(
  AuthInboxRouteChildren,
)

interface AuthRouteChildren {
  AuthInboxRoute: typeof AuthInboxRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthInboxRoute: AuthInboxRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/inbox': typeof AuthInboxRouteWithChildren
  '/inbox/$mailId': typeof AuthInboxMailIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/inbox': typeof AuthInboxRouteWithChildren
  '/inbox/$mailId': typeof AuthInboxMailIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_auth/inbox': typeof AuthInboxRouteWithChildren
  '/_auth/inbox/$mailId': typeof AuthInboxMailIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/about' | '/login' | '/inbox' | '/inbox/$mailId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/about' | '/login' | '/inbox' | '/inbox/$mailId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/login'
    | '/_auth/inbox'
    | '/_auth/inbox/$mailId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/about",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/inbox"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/inbox": {
      "filePath": "_auth.inbox.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/inbox/$mailId"
      ]
    },
    "/_auth/inbox/$mailId": {
      "filePath": "_auth.inbox.$mailId.tsx",
      "parent": "/_auth/inbox"
    }
  }
}
ROUTE_MANIFEST_END */
