/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as InboxIndexImport } from './routes/inbox/index'
import { Route as InboxMailIdImport } from './routes/inbox/$mailId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InboxIndexRoute = InboxIndexImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRoute,
} as any)

const InboxMailIdRoute = InboxMailIdImport.update({
  id: '/inbox/$mailId',
  path: '/inbox/$mailId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/inbox/$mailId': {
      id: '/inbox/$mailId'
      path: '/inbox/$mailId'
      fullPath: '/inbox/$mailId'
      preLoaderRoute: typeof InboxMailIdImport
      parentRoute: typeof rootRoute
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inbox/$mailId': typeof InboxMailIdRoute
  '/inbox': typeof InboxIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inbox/$mailId': typeof InboxMailIdRoute
  '/inbox': typeof InboxIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inbox/$mailId': typeof InboxMailIdRoute
  '/inbox/': typeof InboxIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/inbox/$mailId' | '/inbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/inbox/$mailId' | '/inbox'
  id: '__root__' | '/' | '/about' | '/inbox/$mailId' | '/inbox/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InboxMailIdRoute: typeof InboxMailIdRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InboxMailIdRoute: InboxMailIdRoute,
  InboxIndexRoute: InboxIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/inbox/$mailId",
        "/inbox/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/inbox/$mailId": {
      "filePath": "inbox/$mailId.tsx"
    },
    "/inbox/": {
      "filePath": "inbox/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
