/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as SupportSectionIndexRouteImport } from './routes/support.$section.index'
import { Route as SupportSectionArticleRouteImport } from './routes/support.$section.$article'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRoute,
} as any)
const SupportSectionIndexRoute = SupportSectionIndexRouteImport.update({
  id: '/$section/',
  path: '/$section/',
  getParentRoute: () => SupportRoute,
} as any)
const SupportSectionArticleRoute = SupportSectionArticleRouteImport.update({
  id: '/$section/$article',
  path: '/$section/$article',
  getParentRoute: () => SupportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/blog/$id': typeof BlogIdRoute
  '/blog/': typeof BlogIndexRoute
  '/support/': typeof SupportIndexRoute
  '/support/$section/$article': typeof SupportSectionArticleRoute
  '/support/$section/': typeof SupportSectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog': typeof BlogIndexRoute
  '/support': typeof SupportIndexRoute
  '/support/$section/$article': typeof SupportSectionArticleRoute
  '/support/$section': typeof SupportSectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/blog/$id': typeof BlogIdRoute
  '/blog/': typeof BlogIndexRoute
  '/support/': typeof SupportIndexRoute
  '/support/$section/$article': typeof SupportSectionArticleRoute
  '/support/$section/': typeof SupportSectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/support'
    | '/blog/$id'
    | '/blog/'
    | '/support/'
    | '/support/$section/$article'
    | '/support/$section/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$id'
    | '/blog'
    | '/support'
    | '/support/$section/$article'
    | '/support/$section'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/support'
    | '/blog/$id'
    | '/blog/'
    | '/support/'
    | '/support/$section/$article'
    | '/support/$section/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  SupportRoute: typeof SupportRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/support/$section/': {
      id: '/support/$section/'
      path: '/$section'
      fullPath: '/support/$section/'
      preLoaderRoute: typeof SupportSectionIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/$section/$article': {
      id: '/support/$section/$article'
      path: '/$section/$article'
      fullPath: '/support/$section/$article'
      preLoaderRoute: typeof SupportSectionArticleRouteImport
      parentRoute: typeof SupportRoute
    }
  }
}

interface BlogRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIdRoute: BlogIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface SupportRouteChildren {
  SupportIndexRoute: typeof SupportIndexRoute
  SupportSectionArticleRoute: typeof SupportSectionArticleRoute
  SupportSectionIndexRoute: typeof SupportSectionIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportIndexRoute: SupportIndexRoute,
  SupportSectionArticleRoute: SupportSectionArticleRoute,
  SupportSectionIndexRoute: SupportSectionIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  SupportRoute: SupportRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
