/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthNewImport } from './routes/_auth.new'
import { Route as AuthEditFilterTypeFilterIdImport } from './routes/_auth.edit.$filterType.$filterId'
import { Route as AuthCFilterTypeFilterIdImport } from './routes/_auth.c.$filterType.$filterId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthNewRoute = AuthNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthRoute,
} as any)

const AuthEditFilterTypeFilterIdRoute = AuthEditFilterTypeFilterIdImport.update(
  {
    id: '/edit/$filterType/$filterId',
    path: '/edit/$filterType/$filterId',
    getParentRoute: () => AuthRoute,
  } as any,
)

const AuthCFilterTypeFilterIdRoute = AuthCFilterTypeFilterIdImport.update({
  id: '/c/$filterType/$filterId',
  path: '/c/$filterType/$filterId',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/new': {
      id: '/_auth/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthNewImport
      parentRoute: typeof AuthImport
    }
    '/_auth/c/$filterType/$filterId': {
      id: '/_auth/c/$filterType/$filterId'
      path: '/c/$filterType/$filterId'
      fullPath: '/c/$filterType/$filterId'
      preLoaderRoute: typeof AuthCFilterTypeFilterIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/edit/$filterType/$filterId': {
      id: '/_auth/edit/$filterType/$filterId'
      path: '/edit/$filterType/$filterId'
      fullPath: '/edit/$filterType/$filterId'
      preLoaderRoute: typeof AuthEditFilterTypeFilterIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthNewRoute: typeof AuthNewRoute
  AuthCFilterTypeFilterIdRoute: typeof AuthCFilterTypeFilterIdRoute
  AuthEditFilterTypeFilterIdRoute: typeof AuthEditFilterTypeFilterIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNewRoute: AuthNewRoute,
  AuthCFilterTypeFilterIdRoute: AuthCFilterTypeFilterIdRoute,
  AuthEditFilterTypeFilterIdRoute: AuthEditFilterTypeFilterIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/new': typeof AuthNewRoute
  '/c/$filterType/$filterId': typeof AuthCFilterTypeFilterIdRoute
  '/edit/$filterType/$filterId': typeof AuthEditFilterTypeFilterIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/new': typeof AuthNewRoute
  '/c/$filterType/$filterId': typeof AuthCFilterTypeFilterIdRoute
  '/edit/$filterType/$filterId': typeof AuthEditFilterTypeFilterIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/new': typeof AuthNewRoute
  '/_auth/c/$filterType/$filterId': typeof AuthCFilterTypeFilterIdRoute
  '/_auth/edit/$filterType/$filterId': typeof AuthEditFilterTypeFilterIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/new'
    | '/c/$filterType/$filterId'
    | '/edit/$filterType/$filterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/new'
    | '/c/$filterType/$filterId'
    | '/edit/$filterType/$filterId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/new'
    | '/_auth/c/$filterType/$filterId'
    | '/_auth/edit/$filterType/$filterId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/new",
        "/_auth/c/$filterType/$filterId",
        "/_auth/edit/$filterType/$filterId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/new": {
      "filePath": "_auth.new.tsx",
      "parent": "/_auth"
    },
    "/_auth/c/$filterType/$filterId": {
      "filePath": "_auth.c.$filterType.$filterId.tsx",
      "parent": "/_auth"
    },
    "/_auth/edit/$filterType/$filterId": {
      "filePath": "_auth.edit.$filterType.$filterId.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
