/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLabelLabelIdImport } from './routes/_auth.label.$labelId'
import { Route as AuthCFilterIdIndexImport } from './routes/_auth.c.$filterId.index'
import { Route as AuthCFilterIdContactIdImport } from './routes/_auth.c.$filterId.$contactId'
import { Route as AuthCFilterIdEditContactIdImport } from './routes/_auth.c.$filterId.edit.$contactId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLabelLabelIdRoute = AuthLabelLabelIdImport.update({
  id: '/label/$labelId',
  path: '/label/$labelId',
  getParentRoute: () => AuthRoute,
} as any)

const AuthCFilterIdIndexRoute = AuthCFilterIdIndexImport.update({
  id: '/c/$filterId/',
  path: '/c/$filterId/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthCFilterIdContactIdRoute = AuthCFilterIdContactIdImport.update({
  id: '/c/$filterId/$contactId',
  path: '/c/$filterId/$contactId',
  getParentRoute: () => AuthRoute,
} as any)

const AuthCFilterIdEditContactIdRoute = AuthCFilterIdEditContactIdImport.update(
  {
    id: '/c/$filterId/edit/$contactId',
    path: '/c/$filterId/edit/$contactId',
    getParentRoute: () => AuthRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/label/$labelId': {
      id: '/_auth/label/$labelId'
      path: '/label/$labelId'
      fullPath: '/label/$labelId'
      preLoaderRoute: typeof AuthLabelLabelIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/c/$filterId/$contactId': {
      id: '/_auth/c/$filterId/$contactId'
      path: '/c/$filterId/$contactId'
      fullPath: '/c/$filterId/$contactId'
      preLoaderRoute: typeof AuthCFilterIdContactIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/c/$filterId/': {
      id: '/_auth/c/$filterId/'
      path: '/c/$filterId'
      fullPath: '/c/$filterId'
      preLoaderRoute: typeof AuthCFilterIdIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/c/$filterId/edit/$contactId': {
      id: '/_auth/c/$filterId/edit/$contactId'
      path: '/c/$filterId/edit/$contactId'
      fullPath: '/c/$filterId/edit/$contactId'
      preLoaderRoute: typeof AuthCFilterIdEditContactIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLabelLabelIdRoute: typeof AuthLabelLabelIdRoute
  AuthCFilterIdContactIdRoute: typeof AuthCFilterIdContactIdRoute
  AuthCFilterIdIndexRoute: typeof AuthCFilterIdIndexRoute
  AuthCFilterIdEditContactIdRoute: typeof AuthCFilterIdEditContactIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLabelLabelIdRoute: AuthLabelLabelIdRoute,
  AuthCFilterIdContactIdRoute: AuthCFilterIdContactIdRoute,
  AuthCFilterIdIndexRoute: AuthCFilterIdIndexRoute,
  AuthCFilterIdEditContactIdRoute: AuthCFilterIdEditContactIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/label/$labelId': typeof AuthLabelLabelIdRoute
  '/c/$filterId/$contactId': typeof AuthCFilterIdContactIdRoute
  '/c/$filterId': typeof AuthCFilterIdIndexRoute
  '/c/$filterId/edit/$contactId': typeof AuthCFilterIdEditContactIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/label/$labelId': typeof AuthLabelLabelIdRoute
  '/c/$filterId/$contactId': typeof AuthCFilterIdContactIdRoute
  '/c/$filterId': typeof AuthCFilterIdIndexRoute
  '/c/$filterId/edit/$contactId': typeof AuthCFilterIdEditContactIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/label/$labelId': typeof AuthLabelLabelIdRoute
  '/_auth/c/$filterId/$contactId': typeof AuthCFilterIdContactIdRoute
  '/_auth/c/$filterId/': typeof AuthCFilterIdIndexRoute
  '/_auth/c/$filterId/edit/$contactId': typeof AuthCFilterIdEditContactIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/label/$labelId'
    | '/c/$filterId/$contactId'
    | '/c/$filterId'
    | '/c/$filterId/edit/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/label/$labelId'
    | '/c/$filterId/$contactId'
    | '/c/$filterId'
    | '/c/$filterId/edit/$contactId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/label/$labelId'
    | '/_auth/c/$filterId/$contactId'
    | '/_auth/c/$filterId/'
    | '/_auth/c/$filterId/edit/$contactId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/label/$labelId",
        "/_auth/c/$filterId/$contactId",
        "/_auth/c/$filterId/",
        "/_auth/c/$filterId/edit/$contactId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/label/$labelId": {
      "filePath": "_auth.label.$labelId.tsx",
      "parent": "/_auth"
    },
    "/_auth/c/$filterId/$contactId": {
      "filePath": "_auth.c.$filterId.$contactId.tsx",
      "parent": "/_auth"
    },
    "/_auth/c/$filterId/": {
      "filePath": "_auth.c.$filterId.index.tsx",
      "parent": "/_auth"
    },
    "/_auth/c/$filterId/edit/$contactId": {
      "filePath": "_auth.c.$filterId.edit.$contactId.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
