/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginFa2Import } from './routes/login-fa2'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth.index'
import { Route as AuthUserImport } from './routes/_auth.user'
import { Route as AuthSecurityPasswordImport } from './routes/_auth.security.password'
import { Route as AuthSecurityFa2Import } from './routes/_auth.security.fa2'

// Create/Update Routes

const LoginFa2Route = LoginFa2Import.update({
  id: '/login-fa2',
  path: '/login-fa2',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthUserRoute = AuthUserImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSecurityPasswordRoute = AuthSecurityPasswordImport.update({
  id: '/security/password',
  path: '/security/password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSecurityFa2Route = AuthSecurityFa2Import.update({
  id: '/security/fa2',
  path: '/security/fa2',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/login-fa2': {
      id: '/login-fa2'
      path: '/login-fa2'
      fullPath: '/login-fa2'
      preLoaderRoute: typeof LoginFa2Import
      parentRoute: typeof rootRoute
    }
    '/_auth/user': {
      id: '/_auth/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthUserImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/security/fa2': {
      id: '/_auth/security/fa2'
      path: '/security/fa2'
      fullPath: '/security/fa2'
      preLoaderRoute: typeof AuthSecurityFa2Import
      parentRoute: typeof AuthImport
    }
    '/_auth/security/password': {
      id: '/_auth/security/password'
      path: '/security/password'
      fullPath: '/security/password'
      preLoaderRoute: typeof AuthSecurityPasswordImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthUserRoute: typeof AuthUserRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSecurityFa2Route: typeof AuthSecurityFa2Route
  AuthSecurityPasswordRoute: typeof AuthSecurityPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUserRoute: AuthUserRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthSecurityFa2Route: AuthSecurityFa2Route,
  AuthSecurityPasswordRoute: AuthSecurityPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/login-fa2': typeof LoginFa2Route
  '/user': typeof AuthUserRoute
  '/': typeof AuthIndexRoute
  '/security/fa2': typeof AuthSecurityFa2Route
  '/security/password': typeof AuthSecurityPasswordRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/login-fa2': typeof LoginFa2Route
  '/user': typeof AuthUserRoute
  '/': typeof AuthIndexRoute
  '/security/fa2': typeof AuthSecurityFa2Route
  '/security/password': typeof AuthSecurityPasswordRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/login-fa2': typeof LoginFa2Route
  '/_auth/user': typeof AuthUserRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/security/fa2': typeof AuthSecurityFa2Route
  '/_auth/security/password': typeof AuthSecurityPasswordRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/login-fa2'
    | '/user'
    | '/'
    | '/security/fa2'
    | '/security/password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/login-fa2'
    | '/user'
    | '/'
    | '/security/fa2'
    | '/security/password'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/login-fa2'
    | '/_auth/user'
    | '/_auth/'
    | '/_auth/security/fa2'
    | '/_auth/security/password'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginFa2Route: typeof LoginFa2Route
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginFa2Route: LoginFa2Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login",
        "/login-fa2"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/user",
        "/_auth/",
        "/_auth/security/fa2",
        "/_auth/security/password"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/login-fa2": {
      "filePath": "login-fa2.tsx"
    },
    "/_auth/user": {
      "filePath": "_auth.user.tsx",
      "parent": "/_auth"
    },
    "/_auth/": {
      "filePath": "_auth.index.tsx",
      "parent": "/_auth"
    },
    "/_auth/security/fa2": {
      "filePath": "_auth.security.fa2.tsx",
      "parent": "/_auth"
    },
    "/_auth/security/password": {
      "filePath": "_auth.security.password.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
