/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSharedToRouteImport } from './routes/_auth.shared.$to'
import { Route as AuthMimeMimeTypeRouteImport } from './routes/_auth.mime.$mimeType'
import { Route as AuthFsOwnerIdPathIdRouteImport } from './routes/_auth.fs.$ownerId.$pathId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSharedToRoute = AuthSharedToRouteImport.update({
  id: '/shared/$to',
  path: '/shared/$to',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMimeMimeTypeRoute = AuthMimeMimeTypeRouteImport.update({
  id: '/mime/$mimeType',
  path: '/mime/$mimeType',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFsOwnerIdPathIdRoute = AuthFsOwnerIdPathIdRouteImport.update({
  id: '/fs/$ownerId/$pathId',
  path: '/fs/$ownerId/$pathId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mime/$mimeType': typeof AuthMimeMimeTypeRoute
  '/shared/$to': typeof AuthSharedToRoute
  '/fs/$ownerId/$pathId': typeof AuthFsOwnerIdPathIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mime/$mimeType': typeof AuthMimeMimeTypeRoute
  '/shared/$to': typeof AuthSharedToRoute
  '/fs/$ownerId/$pathId': typeof AuthFsOwnerIdPathIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/mime/$mimeType': typeof AuthMimeMimeTypeRoute
  '/_auth/shared/$to': typeof AuthSharedToRoute
  '/_auth/fs/$ownerId/$pathId': typeof AuthFsOwnerIdPathIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mime/$mimeType'
    | '/shared/$to'
    | '/fs/$ownerId/$pathId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mime/$mimeType'
    | '/shared/$to'
    | '/fs/$ownerId/$pathId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/mime/$mimeType'
    | '/_auth/shared/$to'
    | '/_auth/fs/$ownerId/$pathId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/shared/$to': {
      id: '/_auth/shared/$to'
      path: '/shared/$to'
      fullPath: '/shared/$to'
      preLoaderRoute: typeof AuthSharedToRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mime/$mimeType': {
      id: '/_auth/mime/$mimeType'
      path: '/mime/$mimeType'
      fullPath: '/mime/$mimeType'
      preLoaderRoute: typeof AuthMimeMimeTypeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fs/$ownerId/$pathId': {
      id: '/_auth/fs/$ownerId/$pathId'
      path: '/fs/$ownerId/$pathId'
      fullPath: '/fs/$ownerId/$pathId'
      preLoaderRoute: typeof AuthFsOwnerIdPathIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthMimeMimeTypeRoute: typeof AuthMimeMimeTypeRoute
  AuthSharedToRoute: typeof AuthSharedToRoute
  AuthFsOwnerIdPathIdRoute: typeof AuthFsOwnerIdPathIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMimeMimeTypeRoute: AuthMimeMimeTypeRoute,
  AuthSharedToRoute: AuthSharedToRoute,
  AuthFsOwnerIdPathIdRoute: AuthFsOwnerIdPathIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
